spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-domain.yml
    - classpath:/application-thirdparty.yml
    - optional:classpath:/application-secret.yml

server:
  port: 9000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - prometheus
          - info
          - metrics
