spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-domain.yml

server:
  port: 9000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - prometheus
          - info
          - metrics
