spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-domain.yml
    - classpath:/application-thirdparty.yml
    - optional:classpath:/application-secret.yml

server:
  port: 9000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - prometheus
          - info
          - metrics
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
