spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-domain.yml

server:
  port: 8000
  shutdown: graceful
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      force: true
