spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        query.in_clause_parameter_padding: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false


---
spring.config:
  activate:
    on-profile:
      - local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:ladder;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
      driver-class-name: org.h2.Driver
  redis:
    host: 127.0.0.1
    port: 6379

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace


---
spring.config:
  activate:
    on-profile: test

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:ladder;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
      driver-class-name: org.h2.Driver
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

---
spring.config:
  activate:
    on-profile: dev

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      jdbc-url: ENC(yu9PW30+ULaBB7pB7V2nepnxn+0aqYBnQyiXedYt6K14eS1z8vKJosVm0hYsDfXkCuflBf6HlVfUP9xEgArFQ+adJyKBQwQTiIZdauXZYGz1qUwK51N5JJyzhhfBxTp6B59guFbXnrwjOgZRjV0NtghdGTEPhjUCx3PEr2XHSojnEYu2VZG0MBR2Ii4yLf97JLm1K1tpVcjVBxiWx8WMtg==)
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ENC(IlBCS9vGUY24UAH9DHNcSKQOb3x5EMZ84MnQjwPihd8h8HZXYD12KBxwpZ7KKBZE)
      password: ENC(6KNadT5PUB4bmhFRlrYbm3TNHpOIjOzQPUQUTicix0rnvtpACyu01d3UZiTUL5S2)
  redis:
    host: ENC(JeXnvIZrOFM5ofk1RBmwbM70j6/ZZw4qBNteaY5G+Kq2ER4BjUP4r6kY/Kz8bGS+Mb32KJRUP3ZS3xNGGJzMGbCfQYA5jULbPwy5Q4ZI3tFehCyslOrjsI6HgJXWfcXx)
    port: 6379


---
spring.config:
  activate:
    on-profile: prod
