spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        query.in_clause_parameter_padding: true
    open-in-view: false


---
spring.config:
  activate:
    on-profile:
      - local
      - dev

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:ladder;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
      driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace


---
spring.config:
  activate:
    on-profile: test

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:ladder;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
      driver-class-name: org.h2.Driver

logging:
  level:
    org.hibernate.type.descriptor.sql: trace


---
spring.config:
  activate:
    on-profile: prod
