spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-domain.yml
    - classpath:/application-thirdparty.yml
    - optional:classpath:/application-secret.yml
    - optional:classpath:/application-secret.properties

server:
  port: 9001
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso

management:
  endpoints:
    web:
      base-path: /search
      exposure:
        include:
          - health
          - prometheus
      path-mapping:
        health: /health
        prometheus: /actuator/prometheus
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
