name: Deploy api
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic Versioning (ex. 0.0.1)"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Execute Gradle Jib
        run: ./gradlew :ladder-api:jib -Dimage=${IMAGE} -Dtag=${TAG}
        env:
          IMAGE: mashupladder/ladder-api
          TAG: ${{ github.event.inputs.version }}
      # TODO : Update Helm Chart
